My\Bundle\BlogBundle\Entity\Content:
    type: entity
    table: content
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        article:
            targetEntity: My\Bundle\BlogBundle\Entity\Article
            inversedBy: contents
            joinColumn:
                name: article_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
        area:
            targetEntity: Vince\Bundle\CmsBundle\Entity\Area
            joinColumn:
                name: area_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE