login:
    pattern:   /login
    defaults:  { _controller: VikingMainBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

viking_main_homepage:
    pattern:  /
    defaults: { _controller: VikingMainBundle:Default:index }

viking_admin_homepage:
    pattern:  /admin
    defaults: { _controller: VikingMainBundle:Admin:index }

viking_article_homepage:
    pattern:  /articles
    defaults: { _controller: VikingMainBundle:Article:index }
viking_article_view:
    pattern:  /article/view/{id}
    defaults: { _controller: VikingMainBundle:Article:view }
    requirements:
            id:  \d+
viking_article_edit:
    pattern: /admin/article/edit/{id}
    defaults: { _controller: VikingMainBundle:Article:edit, id: null }
    requirements:
            id:  \d+
