parameters:
#    viking_main.example.class: Viking\MainBundle\Example

services:
#    viking_main.example:
#        class: %viking_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
