ignore_branches:
    - gh-pages
    - i18n
    - search

pre_composer_script: |
    #!/bin/bash

    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/database_user:.*/database_user: root/" app/config/parameters.yml
    sed -i -e "s/database_password:.*/database_password: Secr3t/" app/config/parameters.yml

post_composer_script: |
    #!/bin/bash

    ./app/console doctrine:database:create --no-interaction
    ./app/console project:reset

exclude_patterns:
    - app/autoload.php
    - app/check.php
    - app/SymfonyRequirements.php
    - web/app_*.php
