language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

install:
    - composer self-update

before_script:
    - composer install --dev --prefer-dist --no-interaction
    - php app/console doctrine:database:create --env=test --quiet
    - php app/console doctrine:schema:update --force --env=test

script: phpunit -c app --coverage-text

notifications:
    email:
        - vincentchalamon@gmail.com