language: php

php:
  - 5.3

install:
    - composer self-update

before_script:
    - composer install --dev -n

script: phpunit -c app --coverage-text

after_script:
    - phpdoc

notifications:
    email:
        - vincentchalamon@gmail.com