language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
    - composer self-update
    - composer install --dev --prefer-dist --no-interaction
    - php app/console doctrine:database:create --env=test --quiet
    - php app/console doctrine:schema:update --force --env=test

script:
    - mkdir -p build/logs
    - phpunit -c app --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v

notifications:
    email:
        - vincentchalamon@gmail.com