services:
    my.processor.contact:
        class: My\Bundle\CmsBundle\Processor\ContactProcessor
        parent: vince.processor
        tags:
            -  { name: vince.processor, alias: contact }
        calls:
            - [ setMailer, [ @mailer ] ]
            - [ setTemplating, [ @templating ] ]
            - [ setSession, [ @session ] ]