services:
    my.processor.contact:
        class: My\Bundle\CmsBundle\Processor\ContactProcessor
        parent: vince.processor
        tags:
            -  { name: vince.processor, alias: contact }
        calls:
            - [ setMailer, [ @mailer, %vince.cms.no_reply%, %vince.cms.contact%, %vince.cms.sitename% ] ]
            - [ setTemplating, [ @templating ] ]
            - [ setFlashBag, [ @session.flash_bag ] ]
            - [ setWebDir, [ %kernel.web_dir% ] ]

    my.cms.load.listener:
        class: My\Bundle\CmsBundle\Listener\CmsListener
        tags:
            - { name: kernel.event_listener, event: vince.cms.contact.load, method: onLoadContact }
        calls:
            - [ setFormFactory, [ @form.factory ] ]