services:
    my.cms.load.listener:
        class: My\Bundle\CmsBundle\Listener\CmsListener
        tags:
            - { name: kernel.event_listener, event: vince.cms.load, method: onLoad }
            - { name: kernel.event_listener, event: vince.cms.homepage.load, method: onLoadHomepage }
            - { name: kernel.event_listener, event: vince.cms.cv.load, method: onLoadCV }
            - { name: kernel.event_listener, event: vince.cms.realisations.load, method: onLoadRealisations }
            - { name: kernel.event_listener, event: kernel.response, method: onLoadResponse }
        calls:
            - [ setArticleRepository, [ @vince.repository.article ] ]
            - [ setSkillRepository, [ @my.repository.skill ] ]
            - [ setFormFactory, [ @form.factory ] ]

    my.repository.skill:
        class: Doctrine\ORM\EntityRepository
        arguments: [ My\Bundle\SkillBundle\Entity\Skill ]
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository

    my.processor.contact:
        class: My\Bundle\CmsBundle\Processor\ContactProcessor
        parent: vince.processor
        tags:
            -  { name: vince.processor, alias: contact }
        calls:
            - [ setMailer, [ @mailer ] ]
            - [ setTemplating, [ @templating ] ]
            - [ setSession, [ @session ] ]