services:
    my_cms.admin.category:
        class: My\Bundle\CmsBundle\Admin\Entity\CategoryAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: cms
              label_catalogue: SonataAdminBundle
              label: Catégories
        arguments: [ ~, My\Bundle\CmsBundle\Entity\Category, ~ ]
        calls:
            - [ setTranslationDomain, [ 'SonataAdminBundle' ] ]

    my_cms.processor.contact:
        class: My\Bundle\CmsBundle\Processor\ContactProcessor
        parent: vince_cms.processor
        tags:
            -  { name: vince_cms.processor, alias: contact }
        calls:
            - [ setMailer, [ @mailer, %vince_cms.no_reply%, %vince_cms.contact%, %vince_cms.sitename% ] ]
            - [ setTemplating, [ @templating ] ]
            - [ setFlashBag, [ @session.flash_bag ] ]
            - [ setWebDir, [ %kernel.web_dir% ] ]

    my_cms.listener:
        class: My\Bundle\CmsBundle\Listener\CmsListener
        tags:
            - { name: kernel.event_listener, event: vince_cms.event.load.contact, method: onLoadContact }
        calls:
            - [ setFormFactory, [ @form.factory ] ]
