screenshot:
    pattern: /screenshot.jpg
    defaults: { _controller: MyCmsBundle:Screenshot:generate }

timeline:
    pattern: /timeline.js
    defaults: { _controller: MyCmsBundle:Timeline:index, _format: js }

cv-download:
    pattern: /curriculum-vitae.pdf
    defaults: { _controller: MyCmsBundle:Timeline:downloadAsPdf }