sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:  [admin]
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user: Sonata\UserBundle\Entity\BaseUser
    admin:
        user:
            class:       Sonata\UserBundle\Admin\Entity\UserAdmin
            controller:  SonataAdminBundle:CRUD
            translation: SonataUserBundle

#sonata_doctrine_orm_admin:
    #templates:
        #types:
            #list:
                #localizeddate: AGUserBundle:Admin:localizeddate.html.twig
                #editable: AGUserBundle:Admin:editable.html.twig
            #show:
                #localizeddate: AGUserBundle:Admin:localizeddate.html.twig

sonata_admin:
    title: Vince CMS
    #templates:
        #layout: AGUserBundle:Admin:layout.html.twig
    #dashboard:
        #blocks:
            #- { position: left, type: sonata.admin.block.admin_list }
        #groups:
            #admin.groups.user: ~
            #admin.groups.email: ~
            #admin.groups.configuration: ~