imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@VinceCmsBundle/Resources/config/config.yml" }

parameters:
    router.request_context.host: blog.local
    router.request_context.scheme: http

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
        name: SF2VINCECMS
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [MyCmsBundle, MyQuoteBundle]
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
    assets:
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.0.min.js
            output: js/jquery.min.js
        jquery_ui:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery-ui/jquery-ui.min.js
            output: js/jquery-ui.min.js

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
        mappings:
            tree:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# User
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: My\Bundle\UserBundle\Entity\User
    group:
        group_class: My\Bundle\UserBundle\Entity\Group
    from_email:
        address: no-reply@vincent-chalamon.fr
        sender_name: Blog

# Admin
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:  [admin]
        sonata.block.service.text: ~
        sonata.block.service.action: ~
        sonata.block.service.rss: ~
        sonata.admin.block.search_result: ~

sonata_user:
    security_acl: false
    manager_type: orm
    impersonating:
        route: homepage
    class:
        user: My\Bundle\UserBundle\Entity\User
        group: My\Bundle\UserBundle\Entity\Group
    admin:
        user:
            class:       My\Bundle\UserBundle\Admin\Entity\UserAdmin
            controller:  SonataAdminBundle:CRUD
            translation: SonataUserBundle
        group:
            class:       My\Bundle\UserBundle\Admin\Entity\GroupAdmin
            controller:  SonataAdminBundle:CRUD
            translation: SonataUserBundle

sonata_doctrine_orm_admin:
    templates:
        types:
            list:
                localizeddate: VinceCmsSonataAdminBundle:List:localizeddate.html.twig
                array: VinceCmsSonataAdminBundle:List:array.html.twig
                url: VinceCmsSonataAdminBundle:List:url.html.twig
                html: VinceCmsSonataAdminBundle:List:html.html.twig
                field_tree_up: VinceCmsSonataAdminBundle:List:field_tree_up.html.twig
                field_tree_down: VinceCmsSonataAdminBundle:List:field_tree_down.html.twig
            show:
                localizeddate: VinceCmsSonataAdminBundle:Show:localizeddate.html.twig
                array: VinceCmsSonataAdminBundle:Show:array.html.twig
                url: VinceCmsSonataAdminBundle:Show:url.html.twig
                html: VinceCmsSonataAdminBundle:Show:html.html.twig

sonata_admin:
    title: Vince CMS
    templates:
        layout: VinceCmsSonataAdminBundle::standard_layout.html.twig
    options:
        confirm_exit: false

vince_cms:
    article:
        class: My\Bundle\CmsBundle\Entity\Article
        repository: My\Bundle\CmsBundle\Entity\Repository\ArticleRepository
    block:
        class: My\Bundle\CmsBundle\Entity\Block
    articleMeta:
        class: My\Bundle\CmsBundle\Entity\ArticleMeta
    content:
        class: My\Bundle\CmsBundle\Entity\Content
    menu:
        class: My\Bundle\CmsBundle\Entity\Menu

vince_cms_sonata_admin:
    article: My\Bundle\CmsBundle\Admin\Entity\ArticleAdmin

fos_js_routing:
    routes_to_expose: [redactor-upload]

knp_snappy:
    pdf:
        enabled: true
        binary:  %kernel.root_dir%/../bin/wkhtmltopdf
        options: []
    image:
        enabled: true
        binary:  %kernel.root_dir%/../bin/wkhtmltoimage
        options:
            disable_smart_width: true
            width: 1024
            crop_h: 1024
            quality: 100

liip_imagine:
    filter_sets:
        slider:
            filters:
                thumbnail:
                    size: [558, 300]
                    mode: outbound
        show:
            filters:
                thumbnail:
                    size: [580, 580]
                    mode: outbound
        list:
            filters:
                thumbnail:
                    size: [413, 296]
                    mode: outbound