imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
        grouped:
            type: group
            members: [streamed, swiftylly, swiftantargaz]
        streamed:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        swiftylly:
            type: swift_mailer
            from_email: no-reply@antargaz.fr
            to_email: vincent@ylly.fr
            subject: "Oops : une erreur est survenue dans l'application Antargaz"
            level: debug
        swiftantargaz:
            type: swift_mailer
            from_email: no-reply@antargaz.fr
            to_email: julien.pranville@antargaz.fr
            subject: "Oops : une erreur est survenue dans l'application Antargaz"
            level: debug
        login:
            type: stream
            path: "%kernel.logs_dir%/auth.log"
            level: info
            channels: security
        firephp:
            type:  firephp
            level: info
        chromephp:
            type:  chromephp
            level: info