imports:
    - { resource: parameters.yml }

parameters:
    router.request_context.host: %domain%
    router.request_context.scheme: http

framework:
    #esi:             ~
    translator:      ~
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
        #assets_base_urls: %router.request_context.scheme%://%router.request_context.host%
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/sessions"
        name: SANDBOX
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [MyCmsBundle, SonataUserBundle]
    filters:
        cssrewrite: ~
        yui_css:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

# User
sonata_user:
    security_acl: false
    manager_type: orm
    class:
        user: My\Bundle\UserBundle\Entity\User
        group: My\Bundle\UserBundle\Entity\Group

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: My\Bundle\UserBundle\Entity\User
    group:
        group_class: My\Bundle\UserBundle\Entity\Group
    from_email:
        address: %vince.cms.no_reply%
        sender_name: %vince.cms.sitename%

# CMS
vince_cms:
    tracking_code: %tracking_code%
    sitename: Sandbox
    domain: %domain%
    locales: [fr, en, de, it, es, ru]
    #no_reply: no-reply@sandbox.fr
    #contact: contact@sandbox.fr
    model:
        article:
            class: My\Bundle\CmsBundle\Entity\Article
        block:
            class: My\Bundle\CmsBundle\Entity\Block
        articleMeta:
            class: My\Bundle\CmsBundle\Entity\ArticleMeta
        content:
            class: My\Bundle\CmsBundle\Entity\Content
        menu:
            class: My\Bundle\CmsBundle\Entity\Menu
