imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

doctrine:
    dbal:
        dbname: %database_name%_test

liip_functional_test: ~

ewz_recaptcha:
    enabled: false

swiftmailer:
    disable_delivery: true
