main:
    resource: routing_dev.yml

vince_type:
    resource: "@VinceTypeBundle/Resources/config/routing.yml"

sonata_user:
    resource: "@SonataUserBundle/Resources/config/routing/admin_security.xml"

admin:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"

_sonata_admin:
    resource: .
    type:     sonata_admin