security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    acl:
        connection: default

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        admin:
            pattern:            ^/admin/
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     sonata_user_admin_security_login
                default_target_path: sonata_admin_dashboard
                #use_forward:    false
                check_path:     sonata_user_admin_security_check
                #failure_path:   null
            logout:
                path:           sonata_user_admin_security_logout
                target:         homepage
            anonymous:          true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:            ^/
            context:            user
            switch_user:        true
            form_login:
                provider:       fos_userbundle
                #csrf_provider:  form.csrf_provider
                login_path:     fos_user_security_login
                default_target_path: homepage
                check_path:     fos_user_security_check
                #always_use_default_target_path: true
                #use_referer:    true
            logout:
                path:           fos_user_security_logout
                target:         homepage
            anonymous:          true

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/logout, roles: ROLE_ADMIN }
        - { path: ^/admin/, roles: ROLE_ADMIN }