My\Bundle\SkillBundle\Entity\Skill:
    type: entity
    table: skill
    repositoryClass: My\Bundle\SkillBundle\Entity\Repository\SkillRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        location:
            type: string
            length: 255
        startedAt:
            type: date
            column: started_at
        endedAt:
            type: date
            column: ended_at
            nullable: true
        website:
            type: string
            length: 255
        description:
            type: text
        studies:
            type: boolean
            column: is_studies