My\Bundle\BlogBundle\Entity\Quote:
    type: entity
    table: quote
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        customer:
            type: string
            length: 255
        address:
            type: text
    oneToMany:
        contents:
            targetEntity: My\Bundle\BlogBundle\Entity\QuoteContent
            mappedBy: quote