My\Bundle\QuoteBundle\Entity\Bill:
    type: entity
    table: bill
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
    oneToOne:
        quote:
            targetEntity: My\Bundle\QuoteBundle\Entity\Quote
            cascade: [all]
            joinColumn:
                name: quote_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE