My\Bundle\QuoteBundle\Entity\Customer:
    type: entity
    table: null
    repositoryClass: Vince\Bundle\TypeBundle\Entity\Repository\SearchRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        address:
            type: text
        zipcode:
            type: string
            length: 5
        city:
            type: string
            length: 255
        email:
            type: string
            length: 255
            unique: true
    oneToMany:
        quotes:
            targetEntity: My\Bundle\QuoteBundle\Entity\Quote
            mappedBy: customer
            cascade: [all]