My\Bundle\QuoteBundle\Entity\Delivery:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        contents:
            type: text
        price:
            type: float
    manyToOne:
        quote:
            targetEntity: My\Bundle\QuoteBundle\Entity\Quote
            inversedBy: deliveries
            cascade: [persist]
            joinColumn:
                name: quote_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE