My\Bundle\QuoteBundle\Entity\Quote:
    type: entity
    table: quote
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        notes:
            type: text
        deadline:
            type: date
    oneToMany:
        deliveries:
            targetEntity: My\Bundle\QuoteBundle\Entity\Delivery
            mappedBy: quote
            cascade: [all]
    manyToOne:
        customer:
            targetEntity: My\Bundle\QuoteBundle\Entity\Customer
            inversedBy: quotes
            cascade: [all]
            joinColumn:
                name: customer_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
    oneToOne:
        bill:
            targetEntity: My\Bundle\QuoteBundle\Entity\Bill
            mappedBy: quote
            cascade: [all]