My\Bundle\UserBundle\Entity\User:
    type: entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        address:
            type: text
        zipcode:
            type: string
            length: 5
        city:
            type: string
            length: 255
    manyToMany:
        groups:
            targetEntity: My\Bundle\UserBundle\Entity\Group
            cascade: [persist]
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
            uniqueConstraints:
                user_group_idx:
                    columns: user_id, group_id
