services:
    my.admin.quote:
        class: My\Bundle\QuoteBundle\Admin\Entity\QuoteAdmin
        tags:
            - name: sonata.admin
              manager_type: orm
              group: cms
              label_catalogue: SonataAdminBundle
              label: Devis
        arguments: [ ~, My\Bundle\QuoteBundle\Entity\Quote, ~ ]
        calls:
            - [ setTranslationDomain, [ 'SonataAdminBundle' ] ]
            - [ setDeliveryRepository, [ @my.repository.delivery ] ]
            - [ setObjectManager, [ @doctrine.orm.default_entity_manager ] ]

    my.repository.quote:
        class: Doctrine\ORM\EntityRepository
        arguments: [ My\Bundle\QuoteBundle\Entity\Quote ]
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository

    my.repository.delivery:
        class: Doctrine\ORM\EntityRepository
        arguments: [ My\Bundle\QuoteBundle\Entity\Delivery ]
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository

    my.repository.customer:
        class: Vince\Bundle\TypeBundle\Entity\Repository\SearchRepository
        arguments: [ My\Bundle\QuoteBundle\Entity\Customer ]
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository

    form.type.customer:
        class: My\Bundle\QuoteBundle\Form\Type\CustomerType
        tags:
            - { name: form.type, alias: customer }
        calls:
            - [ setCustomerRepository, [ @my.repository.customer ] ]

    form.type.delivery:
        class: My\Bundle\QuoteBundle\Form\Type\DeliveryType
        tags:
            - { name: form.type, alias: delivery }