My\Bundle\QuoteBundle\Entity\Quote:
    properties:
        notes:
            - NotBlank: ~
        deadline:
            - NotBlank: ~
            - Date: ~
        customer:
            - NotNull: ~
            - Valid: ~
        deliveries:
            - Count:
                min: 1
                max: 999
            - Valid: ~

My\Bundle\QuoteBundle\Entity\Customer:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        name:
            - NotBlank: ~
        address:
            - NotBlank: ~
        zipcode:
            - NotBlank: ~
            - Length:
                min: 5
                max: 5
        city:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email: ~

My\Bundle\QuoteBundle\Entity\Delivery:
    properties:
        contents:
            - NotBlank: ~
        price:
            - NotBlank: ~
            - Type:
                type: float