My\Bundle\BlogBundle\Entity\Quote:
    properties:
        name:
            - NotBlank: ~
        customer:
            - NotBlank: ~
        contents:
            - NotNull: ~

My\Bundle\BlogBundle\Entity\QuoteContent:
    properties:
        quantity:
            - NotBlank: ~
        description:
            - NotBlank: ~
        price:
            - NotBlank: ~
        quote:
            - NotNull: ~