My\Bundle\SkillBundle\Entity\Skill:
    properties:
        title:
            - NotBlank: ~
        location:
            - NotBlank: ~
        startedAt:
            - NotBlank: ~
            - Date: ~
        endedAt:
            - Date: ~
        website:
            - Url: ~
        description:
            - NotBlank: ~