My\Bundle\CmsBundle\Form\Data\Contact:
    properties:
        name:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                checkMX: true
                checkHost: true
        message:
            - NotBlank: ~
            - Length:
                max: 1000
        captcha:
            - EWZ\Bundle\RecaptchaBundle\Validator\Constraints\True: ~
