My\Bundle\CmsBundle\Entity\Article:
    type: entity
    table: article
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        metas:
            targetEntity: My\Bundle\CmsBundle\Entity\ArticleMeta
            mappedBy: article
        contents:
            targetEntity: My\Bundle\CmsBundle\Entity\Content
            mappedBy: article
        menus:
            targetEntity: My\Bundle\CmsBundle\Entity\Menu
            mappedBy: article
    manyToMany:
        categories:
            targetEntity: My\Bundle\CmsBundle\Entity\Category
            joinTable:
                name: article_category
                joinColumns:
                    article_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
            uniqueConstraints:
                event_user_idx:
                    columns: article_id, category_id