My\Bundle\CmsBundle\Entity\Article:
    type: entity
    table: article
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    oneToMany:
        metas:
            targetEntity: My\Bundle\CmsBundle\Entity\ArticleMeta
            mappedBy: article
            orphanRemoval: true
            cascade: [all]
        contents:
            targetEntity: My\Bundle\CmsBundle\Entity\Content
            mappedBy: article
            cascade: [all]
        menus:
            targetEntity: My\Bundle\CmsBundle\Entity\Menu
            mappedBy: article
            cascade: [persist]
