My\Bundle\CmsBundle\Entity\Block:
    type: entity
    table: block
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    manyToOne:
        original:
            targetEntity: My\Bundle\CmsBundle\Entity\Block
            inversedBy: translations
            joinColumn:
                name: original_id
                referencedColumnName: id
                nullable: true
    oneToMany:
        translations:
            targetEntity: My\Bundle\CmsBundle\Entity\Block
            mappedBy: original
            cascade: [persist]
