My\Bundle\CmsBundle\Entity\Category:
    type: entity
    repositoryClass: Vince\Bundle\TypeBundle\Entity\Repository\SearchRepository
    table: category
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255